# Generated by Django 5.1.3 on 2024-11-13 11:12

import django.db.models.deletion
from django.db import migrations, models

import bank.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ATMCard",
            fields=[
                (
                    "card_no",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        validators=[bank.models.validate_card_no],
                    ),
                ),
                ("ac_no", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "card_no",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        validators=[bank.models.validate_card_no],
                    ),
                ),
                ("ac_no", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("cif", models.BigAutoField(primary_key=True, serialize=False)),
                ("pan", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "ph_no",
                    models.CharField(
                        default="0000000000",
                        max_length=10,
                        unique=True,
                        validators=[bank.models.validate_digit_length],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DebitCard",
            fields=[
                (
                    "card_no",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        validators=[bank.models.validate_card_no],
                    ),
                ),
                ("ac_no", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PrepaidCard",
            fields=[
                (
                    "card_no",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                        validators=[bank.models.validate_card_no],
                    ),
                ),
                ("ac_no", models.CharField(max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrentAccount",
            fields=[
                (
                    "ac_no",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ac_holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.customer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CashCreditAccount",
            fields=[
                (
                    "ac_no",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ac_holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.customer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SavingsAccount",
            fields=[
                (
                    "ac_no",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                (
                    "ac_holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.customer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
