# Generated by Django 5.1.3 on 2024-11-26 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import bank.models.cards
import bank.models.products
import bank.models.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                ("ac_no", models.CharField(max_length=20)),
                ("issued", models.DateTimeField(auto_now_add=True)),
                (
                    "expiry",
                    models.DateTimeField(default=bank.models.utils.get_card_expiry),
                ),
                (
                    "card_no",
                    models.CharField(
                        default=bank.models.cards.CreditCard.gen_card_no,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DebitCard",
            fields=[
                ("ac_no", models.CharField(max_length=20)),
                ("issued", models.DateTimeField(auto_now_add=True)),
                (
                    "expiry",
                    models.DateTimeField(default=bank.models.utils.get_card_expiry),
                ),
                (
                    "card_no",
                    models.CharField(
                        default=bank.models.cards.DebitCard.gen_card_no,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("txn_no", models.BigAutoField(primary_key=True, serialize=False)),
                ("initiated", models.DateTimeField(auto_now_add=True)),
                ("amt_txned", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("DR", "Debited"), ("CR", "Credited")], max_length=2
                    ),
                ),
                ("ac_no", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "cif",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "pan",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[bank.models.utils.validate_pan_no],
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "ph_no",
                    models.CharField(
                        default="0000000000",
                        max_length=10,
                        unique=True,
                        validators=[bank.models.utils.validate_phone_no],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CurrentAccount",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "ac_no",
                    models.CharField(
                        default=bank.models.products.CurrentAccount.gen_ac_no,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ac_holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.customer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SavingsAccount",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "ac_no",
                    models.CharField(
                        default=bank.models.products.SavingsAccount.gen_ac_no,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ac_holder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bank.customer"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
